from cave import Cave

# Creating Cave objects
cavern = Cave("Cavern")
cavern.set_description("A dank and dirty cave ")
main_dungeon = Cave("Main Dungeon")
dungeon.set_description("A large cave with a rack")
grotto = Cave("Grotto")
grotto.set_description("A small cave with ancient graffiti")
#Creating more cave objects (from sketch)
cave_entrance = Cave("Cave Entrance")
cave_entrance.set_description("You start here. You're mind is set on hunting the wumpus. It fills you with determination.")
dead_end = Cave("Dead end")
dead_end.set_description("A blank cave wall with no way ahead")
cold_grotto = Cave("Cold Grotto")
grotto.set_description("A small, cold cave with cold ancient graffiti")
open_cavern = Cave("Open Cavern")
open_cavern.set_description("ph")
tunnel = Cave("Tunnel")
tunnel.set_description("A straight cave to squeeze through")
claustrophobic_tunnel = Cave("Claustrophobic Tunnel")
claustrophobic_tunnel.set_description("An even skinnier tunnel that you have to wiggle through")
speleothem_cave = Cave("Speleothem Cave")
speleothem_cave.set_description("A cave with stalactites that hang from the ceiling dripping down water, and stalagmites that spike up from the floor")
cavity = Cave("Cavity")
cavity.set_description("An open part of the cave with a ledge.")
small_grotto = Cave("Small Grotto")
small_grotto.set_description("A smaller cave with small ancient graffiti")
wet_grotto = Cave("Wet Grotto")
wet_grotto.set_description("A small, wet cave with wet ancient graffiti")
deadly_dungeon= Cave("Deadly Dungeon")
deadly_dungeon.set_description("A cave with a plastic human skeleton on the ground. You feel as though his name was Peter.")
deep_cavern  = Cave("Deep Cavern")
deep_cavern.set_description("A large cave with a massive hole that goes as deep as you can see. The only way across is a rickety wooden bridge, stained with wumpus blood")
wumpus = Cave("The Wumpus!")
wumpus.set_description("You found him! Now KILL HIM!!! FOR GLORY!!!")
#directions start
cave_entrance.link_cave()
#bottom line
dead_end.link_cave(cold_grotto, "east")
cold_grotto.link_cave(p, "d")
cold_grotto.link_cave(p, "d")
cold_grotto.link_cave(p, "east")
open_cavern.link_cave(p, "d")
open_cavern.link_cave(p, "d")
open_cavern.link_cave(p, "d")
open_cavern.link_cave(p, "south")
grotto.link_cave(p, "d")
grotto.link_cave(p, "east")
tunnel.link_cave(p, "d")
tunnel.link_cave(p, "north")
#middle line
small_grotto.link_cave(p, "d")
small_grotto.link_cave(p, "east")
cavern.link_cave(cold_grotto, "south")
cavern.link_cave(p, "d")
cavern.link_cave(p, "d")
cavern.link_cave(p, "south")
cavity.link_cave(p, "d")
cavity.link_cave(p, "south")
speleothem_cave.link_cave(p, "d")
speleothem_cave.link_cave(p, "east")
claustrophobic_tunnel.link_cave(p, "d")
claustrophobic_tunnel.link_cave(p, "south")
#top line
wet_grotto.link_cave(p, "east")
wet_grotto.link_cave(p, "south")
deadly_dungeon.link_cave(p, "d")
deadly_dungeon.link_cave(p, "d")
deadly_dungeon.link_cave(p, "south")
deep_cavern.link_cave(p, "d")
deep_cavern.link_cave(p, "east")
main_dungeon.link_cave(p, "d")
main_dungeon.link_cave(p, "d")
main_dungeon.link_cave(p, "south")
wumpus.link_cave(p, "west")