from cave import Cave

# Creating Cave objects
cavern = Cave("Cavern")
cavern.set_description("A dank and dirty cave ")
dungeon = Cave("Main Dungeon")
dungeon.set_description("A large cave with a rack")
grotto = Cave("Grotto")
grotto.set_description("A small cave with ancient graffiti")
#Creating more cave objects (from sketch)
dead_end = Cave("Dead end")
dead_end.set_description("A blank cave wall with no way ahead")
cold_grotto = Cave("Cold Grotto")
grotto.set_description("A small cave that feels strangely cold")
open_cavern = Cave("Open Cavern")
open_cavern.set_description("ph")
tunnel = Cave("Tunnel")
tunnel.set_description("A straight cave to squeeze through")
claustrophobic_tunnel = Cave("Claustrophobic Tunnel")
claustrophobic_tunnel.set_description("An even skinnier tunnel that you have to wiggle through")
speleothem_cave = Cave("Speleothem Cave")
speleothem_cave.set_description("A cave with stalactites that hang from the ceiling dripping down water, and stalagmites that spike up from the floor")
cavity = Cave("Cavity")
cavity.set_description("An open part of the cave with a ledge.")
small_grotto = Cave("Small Grotto")
small_grotto.set_description("A smaller cave with small ancient graffiti")
wet_grotto = Cave("Wet Grotto")
wet_grotto.set_description("A small, wet cave with wet ancient graffiti")
deadly_dungeon= Cave("Deadly Dungeon")
deadly_dungeon.set_description("A cave with a whole human skeleton on the ground./nMade of plastic.")
deep_cavern  = Cave("Deep Cavern")
deep_cavern.set_description("A large cave with a massive hole that goes as deep as you can see. The only way across is a wooden bridge with wumpus blood")
main_dungeon = Cave("Main Dungeon")
main_dungeon.set_description("ph")
wumpus = Cave("The Wumpus!")
wumpus.set_description("ph")